import requests
import sys


URL = 'http://dpaste.com/api/v2/'
DEFAULT_EXPIRE = 1
DEFAULT_SYNTAX = 'text'
DEFAULT_FILE = sys.stdin


# TODO: Add the options for choosing different syntaxes [text by default]
#       Add the options for choosing different expires [1 by default]
#       Choose a different pastebin [dpaste by default]
#       Add some tests


class PyPastebin(object):

    def __init__(self, file=None, syntax=None, expires=None):

        self.file = file
        self.syntax = syntax
        self.expires = expires
        self._status_codes = {
                'OK': 200,
                'Created': 201,
                'Accepted': 202,
                'No content': 204
        }

        if self.file is None:
            self.file = DEFAULT_FILE
        if self.syntax is None:
            self.syntax = DEFAULT_SYNTAX
        if self.expires is None:
            self.expires = DEFAULT_EXPIRE

        self.url = ""
        self.get_url()


    def __str__(self):

        if not self.url:
            return 'No url has been generated.'

        return 'The url is: {} '.format(self.url)


    def get_url(self):
        """Return the url generated by the _generate_url function.

        An exception is raised if the url is not created; return the url
        otherwise.
        """

        try:
            self.url = self._generate_url()
        except:
            raise Exception('It might be there is no content.')


    def _generate_url(self):
        """Return the url of the pastebin if the request was successful.

        If the status_code is not equal to 201, the url will be an empty string.
        """

        response, status_code = self._get_request_info()
        if status_code == self._status_codes['Created']:
            return response.text[:len(response.text)-1]


    def _get_request_info(self):
        """Get the informations about the status code and the response
        of a POST request.

        Status codes:
        200: OK
        201: Created
        202: Accepted
        204: No content
        """
        files = {
                'content': (None, self.file),
                'syntax': (None, self.syntax),
                'expiry_days': (None, self.expires),
        }

        try:
            response = requests.post(URL, files=files)
        except requests.exceptions.RequestException as err:
            print(err)
            return

        status_code = response.status_code

        return response, status_code

if __name__ == '__main__':
    pastebin = PyPastebin()
    print(pastebin)
