import requests
import sys


URL = 'http://dpaste.com/api/v2/'
DEFAULT_EXPIRE = 1
DEFAULT_SYNTAX = 'text'
DEFAULT_FILE = sys.stdin


class PyPastebin(object):

    def __init__(self, file=None, syntax=None, expires=None):
        self.file = file
        self.syntax = syntax
        self.expires = expires
        self._status_codes = {
                'OK': 200,
                'Created': 201,
                'Accepted': 202,
                'No content': 204
        }

        if self.file is None:
            self.file = DEFAULT_FILE
        if self.syntax is None:
            self.syntax = DEFAULT_SYNTAX
        if self.expires is None:
            self.expires = DEFAULT_EXPIRE

        self.files = {
                'content': (None, self.file),
                'syntax': (None, self.syntax),
                'expiry_days': (None, self.expires),
        }

        self._response, self._status_code = self._get_request_info()
        self.url = self.get_url()


    def __str__(self):
        if not self.url:
            return 'No url has been generated.'

        return 'The url is: {} '.format(self.url)


    def get_url(self):
        """Return the url generated by the _generate_url function.

        An exception is raised if the url is not created; return the url
        otherwise.
        """

        try:
            url = self._generate_url()
        except:
            raise Exception('It might be there is no content.')

        return url


    def _generate_url(self):
        """ Return the url of the pastebin.

        If the status_code is not equal to 201, None will be returned.
        """

        if self._status_code == self._status_codes['Created']:
            return self._response.text[:len(self._response.text)-1]

        return None


    def _get_request_info(self):
        """Return the status code and the response of a request.

        Get the info by the request module.

        Status codes:
        200: OK
        201: Created
        202: Accepted
        204: No content
        """

        response = requests.post(URL, files=self.files)
        status_code = response.status_code
        return response, status_code

if __name__ == '__main__':
    pastebin = PyPastebin(syntax='python3')
    print(pastebin)
